### ISSUE TITLE
SAP with Scopus

### ISSUE THREAD

**Issue by srobledog** [coreofscience/python-sap#22]
It would be great to use SAP with data from Scopus

**Comment by odarbelaeze** [comment]
I was checking some scopus exports (together with @dsvalenciah and @jdalzatec) and I can't find a version that has the requirements to build a somewhat precise graph.

To build a graph we have to build a couple functions `article_label` and `citation_label` such that `article_label(article) == citation_label(citation)` for every citation in the bibliography that refers to the article.

We're thinking of using citation parsing using conditional random fields: https://github.com/WING-NUS/Neural-ParsCit, to transform every citation in structured metadata in order to make the mentioned matching.

After we have https://github.com/coreofscience/sap.coreofscience.com deployed we can look deeper into that.

**Comment by odarbelaeze** [comment]
Closed by #23
